export interface MarqueeLanguageItem {
  id: string;
  name: string;
  countryCode: string;
}

export const marqueeLanguages: MarqueeLanguageItem[] = [
  { id: "english", name: "English", countryCode: "gb" },
  { id: "mandarin-chinese", name: "Mandarin Chinese", countryCode: "cn" },
  { id: "hindi", name: "Hindi", countryCode: "in" },
  { id: "spanish", name: "Spanish", countryCode: "es" },
  { id: "modern-standard-arabic", name: "Modern Standard Arabic", countryCode: "sa" },
  { id: "french", name: "French", countryCode: "fr" },
  { id: "bengali", name: "Bengali", countryCode: "bd" },
  { id: "portuguese", name: "Portuguese", countryCode: "pt" },
  { id: "russian", name: "Russian", countryCode: "ru" },
  { id: "indonesian", name: "Indonesian", countryCode: "id" },
  { id: "urdu", name: "Urdu", countryCode: "pk" },
  { id: "standard-german", name: "Standard German", countryCode: "de" },
  { id: "japanese", name: "Japanese", countryCode: "jp" },
  { id: "nigerian-pidgin", name: "Nigerian Pidgin", countryCode: "ng" },
  { id: "egyptian-arabic", name: "Egyptian Arabic", countryCode: "eg" },
  { id: "marathi", name: "Marathi", countryCode: "in" },
  { id: "vietnamese", name: "Vietnamese", countryCode: "vn" },
  { id: "telugu", name: "Telugu", countryCode: "in" },
  { id: "hausa", name: "Hausa", countryCode: "ng" },
  { id: "turkish", name: "Turkish", countryCode: "tr" },
  { id: "western-punjabi", name: "Western Punjabi", countryCode: "pk" },
  { id: "swahili", name: "Swahili", countryCode: "ke" },
  { id: "tagalog", name: "Tagalog", countryCode: "ph" },
  { id: "tamil", name: "Tamil", countryCode: "in" },
  { id: "yue-chinese", name: "Yue Chinese (incl. Cantonese)", countryCode: "hk" },
  { id: "wu-chinese", name: "Wu Chinese", countryCode: "cn" },
  { id: "iranian-persian", name: "Iranian Persian", countryCode: "ir" },
  { id: "korean", name: "Korean", countryCode: "kr" },
  { id: "thai", name: "Thai", countryCode: "th" },
  { id: "javanese", name: "Javanese", countryCode: "id" },
  { id: "italian", name: "Italian", countryCode: "it" },
  { id: "gujarati", name: "Gujarati", countryCode: "in" },
  { id: "levantine-arabic", name: "Levantine Arabic", countryCode: "lb" },
  { id: "amharic", name: "Amharic", countryCode: "et" },
  { id: "kannada", name: "Kannada", countryCode: "in" },
  { id: "bhojpuri", name: "Bhojpuri", countryCode: "in" },
  { id: "sudanese-arabic", name: "Sudanese Arabic", countryCode: "sd" },
  { id: "polish", name: "Polish", countryCode: "pl" },
  { id: "chinese-jinyu", name: "Chinese, Jinyu", countryCode: "cn" },
  { id: "ukrainian", name: "Ukrainian", countryCode: "ua" },
  { id: "chinese-xiang", name: "Chinese, Xiang", countryCode: "cn" },
  { id: "malayalam", name: "Malayalam", countryCode: "in" },
  { id: "chinese-hakka", name: "Chinese, Hakka", countryCode: "cn" },
  { id: "oriya-odia", name: "Oriya (Odia)", countryCode: "in" },
  { id: "burmese", name: "Burmese", countryCode: "mm" },
  { id: "panjabi-eastern", name: "Panjabi, Eastern", countryCode: "in" },
  { id: "sunda", name: "Sunda", countryCode: "id" },
  { id: "romanian", name: "Romanian", countryCode: "ro" },
  { id: "maithili", name: "Maithili", countryCode: "in" },
  { id: "azerbaijani", name: "Azerbaijani", countryCode: "az" },
];
